### ISSUE TITLE
Comment about constants formatting 

### ISSUE THREAD

**Issue by DavidTheExplorer** [robertvazan/noexception#4]
The `Exceptions` class has a bunch of constants whose names should really be uppercase for clarity + convention :)

**Comment by robertvazan** [comment]
Yeah, I get a lot of these comments. My personal style is to uppercase only actual constants rather than all static final fields. It might look weird to you, but I instead find it weird to uppercase variables that are not constants by nature. I guess it's a habit from C++.

**Comment by DavidTheExplorer** [comment]
I didn't look into the code deeply, can you explain what you mean by "nature"? If it's the immutability of the objects, they are still constant.
Since the project is open source, I highly recommend following the convention because it's the first thing that stands out - So people might mistakenly assume the project was made by a novice developer, and not use it.

**Comment by robertvazan** [comment]
Constant by nature means something you would `#define` as a C++ macro: number, string, small value object. I think it's the value nature that makes the difference: no object identity, transparent content, indistinguishable copies. So a Date or a record would be constant. Interface implementations are not.

BTW, I *would* follow conventions if there were any. Unfortunately, unlike Rust or Go, Java does not have any universally accepted conventions, not even for tabs vs. spaces or for maximum line length, never mind indentation rules or newlines/wrapping. I don't complain. I instead take advantage of the situation and invent my own conventions :-)

**Comment by DavidTheExplorer** [comment]
What? Of course there are [official conventions](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf) for everything you mentioned, around 95% are universal.
Under "_Naming Conventions_" check out "_Constants_".

Again, I'm just saying what an experienced developer would likely feel and the probable effect.
It's your project so I'm not going to convince you anymore, I just say this because I like the project so I care.

**Comment by robertvazan** [comment]
Those are Sun's original conventions used for JDK code. Google has [its own conventions](https://google.github.io/styleguide/javaguide.html). IDEs come with their own presets. Eclipse has two Eclipse-specific formatter presets and I suspect IDEA has one of its own. Lots of other conventions can be found on the Internet.

The reason for this is that Java is one of the older languages that predate GitHub. Code style was meant to be project-specific back then. Newer languages like Go and Rust are designed for online collaboration, so they come with rigid formatting rules and built-in formatting tools to minimize diff noise.
